# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CheeseBurgerYummy' do
	pod 'Alamofire'
	pod 'SwiftyJSON'
end

target 'CheeseBurgerYummyTests' do

end

target 'CheeseBurgerYummyUITests' do

end

